# Generated by Django 5.0.2 on 2024-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_chatpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
        
    ]
