# Generated by Django 5.0.2 on 2024-02-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_chatpost_like_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
